AllCops:
  Exclude:
  - node_modules/**/*
  - vendor/**/*
  - tmp/**/*
  DisplayCopNames: false
  DisabledByDefault: true
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  ActiveSupportExtensionsEnabled: true

inherit_from:
  - config/bundler.yml
  - config/capybara.yml
  - config/discourse.yml
  - config/factory_bot.yml
  - config/gitlab-security.yml
  - config/graphql.yml
  - config/layout.yml
  - config/lint.yml
  - config/metrics.yml
  - config/naming.yml
  - config/performance.yml
  - config/rails.yml
  - config/rake.yml
  - config/rspec.yml
  - config/rspec_rails.yml
  - config/security.yml
  - config/style.yml

inherit_mode:
  merge:
    - Exclude
