require: rubocop-graphql

inherit_gem:
  rubocop-graphql: config/default.yml

GraphQL/ArgumentDescription:
  Enabled: false
GraphQL/FieldDescription:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
