Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/BigDecimalNew:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/BooleanSymbol:
  Enabled: true
Lint/CircularArgumentReference:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateCaseCondition:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateHashKey:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EachWithObjectArgument:
  Enabled: true
Lint/ElseLayout:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/EmptyWhen:
  Enabled: true
Lint/EnsureReturn:
  Enabled: true
Lint/FlipFlop:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/FloatOutOfRange:
  Enabled: true
Lint/FormatParameterMismatch:
  Enabled: true
Lint/HashCompareByIdentity:
  Enabled: true
Lint/HeredocMethodCallPosition:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/ImplicitStringConcatenation:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/IneffectiveAccessModifier:
  Enabled: true
Lint/InheritException:
  Enabled: true
  EnforcedStyle: standard_error
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LiteralAsCondition:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/LiteralInInterpolation:
  Enabled: true
Lint/Loop:
  Enabled: true
Lint/MissingCopEnableDirective:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/MultipleComparison:
  Enabled: true
Lint/NestedMethodDefinition:
  Enabled: true
Lint/NextWithoutAccumulator:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NonDeterministicRequireOrder:
  Enabled: true
Lint/NonLocalExitFromIterator:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Lint/PercentStringArray:
  Enabled: true
Lint/PercentSymbolArray:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/RandOne:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: true
Lint/RedundantCopEnableDirective:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RedundantRequireStatement:
  Enabled: true
Lint/RedundantSafeNavigation:
  Enabled: true
Lint/RedundantSplatExpansion:
  Enabled: true
Lint/RedundantStringCoercion:
  Enabled: true
Lint/RedundantWithIndex:
  Enabled: true
Lint/RedundantWithObject:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RegexpAsCondition:
  Enabled: true
Lint/RequireParentheses:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/RescueType:
  Enabled: true
Lint/ReturnInVoidContext:
  Enabled: true
Lint/SafeNavigationChain:
  Enabled: true
  AllowedMethods:
  - present?
  - blank?
  - presence
  - try
  - try!
  - to_bool
  - to_liquid
  - in?
Lint/SafeNavigationWithEmpty:
  Enabled: true
Lint/ScriptPermission:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/SendWithMixinArgument:
  Enabled: true
Lint/ShadowedException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/ToJSON:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnifiedInteger:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UriEscapeUnescape:
  Enabled: true
Lint/UriRegexp:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Lint/Void:
  Enabled: true
