plugins: rubocop-rake

Rake/ClassDefinitionInTask:
  Enabled: true
Rake/Desc:
  Enabled: true
Rake/DuplicateNamespace:
  Enabled: true
Rake/DuplicateTask:
  Enabled: true
Rake/MethodDefinitionInTask:
  Enabled: true
