Security/CompoundHash:
  Enabled: true
Security/Eval:
  Enabled: true
Security/IoMethods:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/Open:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
