files_to_lint: '\.(erb|haml|js|jsx|liquid|md|rb|ts|tsx)$'
whitelist:
  - '^(?:[0-9a-fA-F]{3}){2}$' # hex colors, e.g. ffffff
  - '^[mp][abhlrtv]xxx?l$' # CSS class names, e.g. pvxxxl
  - ^sub        # subclass, subquery, subnet
  - '[ai]ble$'  # joinable, deletable, invertible
  - '[eo]rs?$'  # accessor, shortener, approvers
  - ify$        # stringify, regexpify
  - ified$      # stringified
  - ized?$      # tableize, parameterize, parameterized
  - ^XX         # front-end fancy component preloader text placeholder
